-- MySQL Script generated by MySQL Workbench
-- Sat Dec 27 14:33:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema energy_monitoring_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema energy_monitoring_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `energy_monitoring_database` DEFAULT CHARACTER SET utf8mb4 ;
USE `energy_monitoring_database` ;

-- -----------------------------------------------------
-- Table `energy_monitoring_database`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energy_monitoring_database`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `is_active` TINYINT(1) ZEROFILL UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energy_monitoring_database`.`coordinators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energy_monitoring_database`.`coordinators` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `mac` VARCHAR(16) NOT NULL,
  `ip` VARCHAR(15) NULL DEFAULT NULL,
  `port` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `status` ENUM('online', 'offline', 'error') NOT NULL DEFAULT 'offline',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `energy_monitoring_database`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energy_monitoring_database`.`meters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energy_monitoring_database`.`meters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `coordinator_id` INT UNSIGNED NOT NULL,
  `zb_long_addr` VARCHAR(23) NOT NULL,
  `zb_short_addr` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `status` ENUM('online', 'offline', 'error') NOT NULL DEFAULT 'offline',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen` TIMESTAMP NULL DEFAULT NULL,
  `voltage` DECIMAL(10,2) NULL DEFAULT NULL,
  `current` DECIMAL(10,2) NULL DEFAULT NULL,
  `active_power` DECIMAL(10,2) NULL DEFAULT NULL,
  `reactive_power` DECIMAL(10,2) NULL DEFAULT NULL,
  `apparent_power` DECIMAL(10,2) NULL DEFAULT NULL,
  `power_factor` DECIMAL(10,2) NULL DEFAULT NULL,
  `frequency` DECIMAL(10,2) NULL DEFAULT NULL,
  `neutral_current` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `coordinator_id_idx` (`coordinator_id` ASC) VISIBLE,
  CONSTRAINT `coordinator_id`
    FOREIGN KEY (`coordinator_id`)
    REFERENCES `energy_monitoring_database`.`coordinators` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energy_monitoring_database`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energy_monitoring_database`.`logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `coordinator_id` INT UNSIGNED NOT NULL,
  `meter_id` INT UNSIGNED NOT NULL,
  `type` ENUM('info', 'warning', 'error', 'command') NOT NULL DEFAULT 'info',
  `message` TEXT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `coordinator_id_idx` (`coordinator_id` ASC) VISIBLE,
  INDEX `meter_id_idx` (`meter_id` ASC) VISIBLE,
  CONSTRAINT `coordinator_id`
    FOREIGN KEY (`coordinator_id`)
    REFERENCES `energy_monitoring_database`.`coordinators` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `meter_id`
    FOREIGN KEY (`meter_id`)
    REFERENCES `energy_monitoring_database`.`meters` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
